# Spring Datasource
spring.datasource.url=jdbc:h2:mem:petroconnectdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Session Configuration
server.servlet.session.timeout=30m
spring.session.store-type=memory

# Enable H2 Console (for development only)
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false